server:
  port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        input:
          group: payments
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json

#api:
#  url:
#    reserve: http://localhost:8081

---
spring:
  profiles: docker
#  sleuth:
#    sampler:
#      probability: 1
#    web:
#      skipPattern: (^cleanup.*|.+favicon.*)
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        input:
          group: payments
          destination: pcroom
          contentType: application/json
        output:
          destination: pcroom
          contentType: application/json

api:
  url:
    gateway5: http://gateway5:8080
    order5: http://order5:8080
    seat5: http://seat5:8080
    payment5: http://payment5:8080
